# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5.QtCore
#import can
from PyQt5 import QtCore, QtGui, QtWidgets
import Utility
import os
#from time import sleep
import RealMainWindow
import PreMadeWindow
import SaveMessageWindow
import PasswordWindow
import ManMadeWindow
import AddNewMessages

class Worker(QtCore.QObject):

    finished = QtCore.pyqtSignal()
    progress = QtCore.pyqtSignal(str)

    def run(self):
        print("Starting the reading worker gui thread")
        i = 0
        j = 0
        while 1 :
            if i == 700000 :
                msg = Utility.testOneCan()
                i = 0
                if msg == "" or msg == None :
                    if j == 0:
                        self.progress.emit("NoMessages")
                        j=1
                    else:
                        None
                else :
                    self.progress.emit(msg)
                    j = 0
            else :
                i = i+1

        self.finished.emit()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow2 = QtWidgets.QMainWindow()
    MainWindow3 = QtWidgets.QMainWindow()
    MainWindow4 = QtWidgets.QMainWindow()
    MainWindow5 = QtWidgets.QMainWindow()
    MainWindow6 = QtWidgets.QMainWindow()
    ui = RealMainWindow.Ui_MainWindow()
    ui2 = PreMadeWindow.Ui_MainWindow2()
    ui3 = ManMadeWindow.Ui_MainWindow3()
    ui4 = AddNewMessages.Ui_MainWindow4()
    ui5 = SaveMessageWindow.Ui_MainWindow5()
    ui6 = PasswordWindow.Ui_MainWindow6()
    ui.setupUi(MainWindow,MainWindow2,MainWindow3,MainWindow4,MainWindow6)
    ui2.setupUi(MainWindow2,MainWindow3)
    ui3.setupUi(MainWindow3,MainWindow2,MainWindow5)
    ui4.setupUi(MainWindow4)
    ui5.setupUi(MainWindow5)
    ui6.setupUi(MainWindow6)
    MainWindow.show()
    sys.exit(app.exec_())

#TODO
# 22-Make the windows app. -> You can use os.system for cmd too, so maybe we can make only one app and add a window at the beggining that will make you choose which os you are working on. Or even better, you can just chech with os you are working on, import platform. platform.system() -> Linux, Windows, Darwin.
# 2-Refactor and divide-> Done
# 3-Fix ui bug, Qtthread. -> almost there.
# 4-Add new python threads instead of ui threads. -> Used this but not really.
# 5-Learn to use QWidgets.
# 6-Add tx to the premade messages -> Done
# 7-Add filter to the read display, like only show with x id...
# 8-Stop hardcoding the frecuency in connectCan, need to add a new window.
# 9-Translate the error messages to readable text.
# 10-Use as less global variables as possible.
# 11-Try to add the messages and password inside the app so we don't have to copy it.
# 12-IF 11 doesn't work, learn how to encrypt the password file.
# 13-Remove delay from qtthread and fix it if 3 or 4 doesn't work -> 3 and 4 on the go.
# 14-Update the guide if needed, maybe add a video in the future to show the app.
# 15-Add label to id and data in the manmademessage.
# 16-Add a box for each byte -> Choose from both.
# 17-Add a label to say if the new message was save.
# 18-Fix bug new premade message doesnt appear(refresh viewlist every second or so).
# 19-Test explorer.
# 20-Add better commentary and traces.
# 21-Fix Readme
# 22-Stop reading the same message if no new message in the bus.
